### 8. Analytical Hierarchy Process (AHP)

Alternatif:
- Yamaha
- Honda
- Suzuki
- Kawasaki

Kriteria:
- Gaya
- Keandalan
- Keenomisan

Preferensi Kriteria
1. Keandalan 2x Gaya
2. Gaya 3x Keenomisan
3. Keandalan 4x keenomisan

Preferensi Alternatif
1. Gaya: Kawasaki > Honda > Yamaha > Suzuki
2. Keandalan: Honda > Yamaha > Kawasaki > Suzuki
3. Keandalan 4x keekonomisan

In [1]:
import numpy as np

8.1 Fungsi Normalisasi

In [5]:
def calc_norm(M):
    print ('Normalisasi Matriks')
    if M.ndim == 1 :
        sM = np.sum(M)
        return M/sM
    else:
        sM = np.sum(M, axis = 0)
        return M/sM

8.2 Matriks kriteria dan Eigen Vektor

In [6]:
MPBK = np.array([
    [1/1, 1/2, 3/1],
    [2/1, 1/1, 4/1],
    [1/3, 1/4, 1/1]
])

print(MPBK)

[[1.         0.5        3.        ]
 [2.         1.         4.        ]
 [0.33333333 0.25       1.        ]]


8.3 Normalisasi

In [10]:
w_MPB = calc_norm(MPBK)
print(w_MPB)

Normalisasi Matriks
[[0.3        0.28571429 0.375     ]
 [0.6        0.57142857 0.5       ]
 [0.1        0.14285714 0.125     ]]


8.4 Eigen Vektor

In [11]:
m, n = w_MPB.shape
V = np.zeros(m)
for i in range(m):
    V[i] = np.sum(w_MPB[i, :])

print('Eigen Vector')
w_MPB = V / m
print(w_MPB)

Eigen Vector
[0.3202381  0.55714286 0.12261905]


8.5 Matriks dan Eigen Vector Alternatif

a. Alternatif Gaya

In [13]:
print('MPg : Alternatif Kualitatif Berpasangan')
AKB_G = np.array([
    [1/1, 1/2, 2/1, 1/3],
    [2/1, 1/1, 3/1, 1/2],
    [1/2, 1/3, 1/1, 1/4],
    [3/1, 2/1, 4/1, 1/1]
])

print(AKB_G)

MPg : Alternatif Kualitatif Berpasangan
[[1.         0.5        2.         0.33333333]
 [2.         1.         3.         0.5       ]
 [0.5        0.33333333 1.         0.25      ]
 [3.         2.         4.         1.        ]]


- normalisasi

In [15]:
w_G = calc_norm(AKB_G)
print(w_G)

Normalisasi Matriks
[[0.15384615 0.13043478 0.2        0.16      ]
 [0.30769231 0.26086957 0.3        0.24      ]
 [0.07692308 0.08695652 0.1        0.12      ]
 [0.46153846 0.52173913 0.4        0.48      ]]


- Eigen Vector

In [16]:
m, n = w_G.shape
V = np.zeros(m)
for i in range(m):
    V[i] = np.sum(w_G[i, :])

print('Eigen Vector')
w_G = V / m
print(w_G)

Eigen Vector
[0.16107023 0.27714047 0.0959699  0.4658194 ]


b. Alternatif Keandalan

In [17]:
print('MPa : Alternatif Kualitatif Berpasangan')
AKB_A = np.array([
    [1/1, 1/2, 3/1, 2/1],
    [2/1, 1/1, 4/1, 3/1],
    [1/3, 1/4, 1/1, 1/2],
    [1/2, 1/3, 2/1, 1/1]
])

print(AKB_A)

MPa : Alternatif Kualitatif Berpasangan
[[1.         0.5        3.         2.        ]
 [2.         1.         4.         3.        ]
 [0.33333333 0.25       1.         0.5       ]
 [0.5        0.33333333 2.         1.        ]]


- Normalisasi

In [18]:
w_A = calc_norm(AKB_A)
print(w_A)

Normalisasi Matriks
[[0.26086957 0.24       0.3        0.30769231]
 [0.52173913 0.48       0.4        0.46153846]
 [0.08695652 0.12       0.1        0.07692308]
 [0.13043478 0.16       0.2        0.15384615]]


- Eigen Vector

In [19]:
m, n = w_A.shape
V = np.zeros(m)
for i in range(m):
    V[i] = np.sum(w_A[i, :])

print('Eigen Vector')
w_A = V / m
print(w_A)

Eigen Vector
[0.27714047 0.4658194  0.0959699  0.16107023]


c. Alternatif Keekonomisan

In [29]:
print('Perbandingan Keekonomisan Bahan Bakar : Alternatif Kuantitatif')
ym = 60
hn = 80
sz = 60
kw = 80

ACM_Fe = np.array([ym, hn, sz, kw])
print(ACM_Fe)

Perbandingan Keekonomisan Bahan Bakar : Alternatif Kuantitatif
[60 80 60 80]


- normalisasi

In [30]:
w_E = calc_norm(ACM_Fe)
print(w_E)

Normalisasi Matriks
[0.21428571 0.28571429 0.21428571 0.28571429]


d. Gabung Nilai Eigen Vector

In [32]:
wM = np.column_stack([w_G, w_A, w_E])
print(wM)

[[0.16107023 0.27714047 0.21428571]
 [0.27714047 0.4658194  0.28571429]
 [0.0959699  0.0959699  0.21428571]
 [0.4658194  0.16107023 0.28571429]]


e. Menghitung Score Akhir

In [35]:
print('Nilai Akhir untuk : Y, H, S, K')
MC_Score = np.dot(wM, w_MPB)
print(MC_Score)

Nilai Akhir untuk : Y, H, S, K
[0.23226317 0.3833129  0.11047767 0.27394626]


Mencari Motor Terbaik

In [36]:
print('Nilai motor terbaik terpilih berdasarkan manfaat kriteria')
Max_Motor_Score = np.max(MC_Score)
print(Max_Motor_Score)

Nilai motor terbaik terpilih berdasarkan manfaat kriteria
0.3833128995745455
