### 2. Matriks

2.1 Pendefinisian Matriks

In [1]:
import numpy as np

In [8]:

#Skalar
scalar = np.array(5)
print("Skalar:\n", scalar)

#Vektor baris (1xn)
vector_row = np.array([1, 2, 3])
print("Vektor baris: ", vector_row)
print("\n")

#Matriks 2D
matrix = np.array([[1,2,3],[4,5,6]])
print("Matriks 2D:\n", matrix)

#Matriks 3D
matrix_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriks 3D:\n", matrix_3d)

Skalar:
 5
Vektor baris:  [1 2 3]


Matriks 2D:
 [[1 2 3]
 [4 5 6]]
Matriks 3D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


2.2 Operasi Matriks

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#Penjumlahan
C = A + B
print("Hasil penjumlahan: \n", C)

#Pengurangan
D = A - B
print("Hasil pengurangan: \n", D)

#Perkalian
E = np.dot(np.dot(A, B), C) #atau E = A * B
print("Hasil perkalian: \n", E)

#Tranpose
F = np.transpose(A) #atau A.T
print("Hasil transpose: \n", F)

Hasil penjumlahan: 
 [[ 6  8]
 [10 12]]
Hasil pengurangan: 
 [[-4 -4]
 [-4 -4]]
Hasil perkalian: 
 [[334 416]
 [758 944]]
Hasil transpose: 
 [[1 3]
 [2 4]]


2.3 Operasi Elemen pada Matriks

In [12]:
G = A * B #klo bintang dikali perelemen klo dot dikali matriksnya
print("Perkalian per elemen:\n", G)

H = A**2
print("Pangkat elemen:\n", H)

Perkalian per elemen:
 [[ 5 12]
 [21 32]]
Pangkat elemen:
 [[ 1  4]
 [ 9 16]]


2.4 Penyelesaian SPL Matriks

In [13]:
# x + 2y = 10
# 3x + 4y = 24

A = np.array([[1,2],[3,4]])
B = np.array([10,24])

# Solve the system of equations
X = np.linalg.solve(A, B)
print("Hasil: ", X)

Hasil:  [4. 3.]


2.5 Manipulasi

In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#Penggabungan Horizontal
H = np.hstack((A, B))
print("Hasil:\n", H)

#Penggabungan Vertikal
H = np.vstack((A, B))
print("Hasil:\n", H)

Hasil:
 [[1 2 5 6]
 [3 4 7 8]]
Hasil:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
